### ISSUE TITLE
the new "loved" category gives "unranked error" instead of falling back on oppai

### ISSUE THREAD

**Issue by omkelderman** [Tillerino/Tillerinobot#100]
![](https://cdn.discordapp.com/attachments/170177781257207808/237559744867467264/screenshot052.jpg)

new loved category:
- https://osu.ppy.sh/news/151925254083
- https://osu.ppy.sh/p/beatmaplist?m=-1&r=12&g=0&la=0&ra=

**Comment by Tillerino** [comment]
Oh okay, that should be a pretty simple fix.

**Comment by omkelderman** [comment]
would think so, but I couldnt find a place to fix it, so I'm guessing it's in the backend part :P

**Comment by omkelderman** [comment]
ah, and aparently it has been apped to API documentation:
![](https://omk.pics/1/PMWwd.png)

**Comment by Tillerino** [comment]
Should be working now. (I added oppai-only mode for WIP and graveyard as
well for that matter)

**Comment by omkelderman** [comment]
Can't you do something like "everything except ranked(like)"? Idk :p

**Comment by Tillerino** [comment]
You never know if how you want to treat _everything else_ until it shows up.

**Comment by omkelderman** [comment]
is this resolved now btw?

**Comment by Tillerino** [comment]
I thought so, yeah. You wanna check a loved map real quick?

**Comment by MrMorkat** [comment]
works fine :D

**Comment by omkelderman** [comment]
> works fine :D

Ok, i'll close this for now then.

**Comment by Tillerino** [comment]
Thank you
