### ISSUE TITLE
Bigger future pp than 100%

### ISSUE THREAD

**Issue by Hitmare0** [Tillerino/Tillerinobot#109]
the last message from tillerino on the bottom of the screen with the false future pp
![screenshot076](https://cloud.githubusercontent.com/assets/24482038/21060380/53973cc2-be47-11e6-873f-91db97f6faa2.png)

**Comment by omkelderman** [comment]
you're saying you cant get more then 100% pp? pfff n00b Keepo

But for realz, @Tillerino can you look into this?

**Comment by Tillerino** [comment]
Fixed in 58f78a5
