### ISSUE TITLE
Recommend command displays DT instead of NC

### ISSUE THREAD

**Issue by AiAe** [Tillerino/Tillerinobot#113]

**Comment by omkelderman** [comment]
to clarify, when doing `!r NC` it gives `DT` recomendations cuz they are basically the same xd

**Comment by dp-p** [comment]
no they are not the same! :)

**Comment by omkelderman** [comment]
they are pp/score/whatever wise

**Comment by dp-p** [comment]
But they are not named the same so its bothers me

**Comment by omkelderman** [comment]
yeah yeay ;;
