### ISSUE TITLE
Enter score parameters to get PP calculations for non-FC scores

### ISSUE THREAD

**Issue by Rickput** [Tillerino/Tillerinobot#12]
Currently, getting the PP value for scores are pretty basic and you can't get PP values for non-FC scores, as Tillerino just assumes it's a FC.

I propose to add a new command where you can enter the exact parameters for a specific score. For example:

!score 600g 34k 1b 3m 867x

Where g = 300, k = 100, b = 50, m = miss, x = combo. (Value labels subject to change)

This will also make an almost-FC score where a combo point was missed on a slider get a more accurate PP value.

**Comment by Drunkguy101** [comment]
Does the amount of misses effect PP? Wouldn't it only be the max combo? I'd be okay with something like this:
[code]!acc 97.1 867x

**Comment by Tillerino** [comment]
No, the amount of misses plays a role.

**Comment by Drunkguy101** [comment]
Ah I see, thanks

**Comment by Tillerino** [comment]
Implemented.
