### ISSUE TITLE
np handler *sometimes* says map doesnt exist

### ISSUE THREAD

**Issue by omkelderman** [Tillerino/Tillerinobot#122]
Beatmap: https://osu.ppy.sh/s/106443

First reported on discord:
![](https://osu.ppy.sh/ss/7296898)
![](https://osu.ppy.sh/ss/7296944)

Can replicate, but it gets really weird, the same diff gets both a "doesnt exist" error and a reply with info.... So I have noooo idea what the heck is going on there:
![](https://omk.pics/1/GSf9Z.png)
(The [Terror] and [Another] diff both have a response and an error)

**Comment by Tillerino** [comment]
The beatmap files are empty. See ppy/osu-api#171
