### ISSUE TITLE
!with reporting it doesnt have info for mods, but its ok in /np with mods and in the api, but only sometimes

### ISSUE THREAD

**Issue by omkelderman** [Tillerino/Tillerinobot#123]
![screenshot](https://omk.pics/1/SHS4Y.png)

Beatmap: https://osu.ppy.sh/b/746471&m=0

* first message being a "normal" `/np` - works
* second message a `!with hddt` - does not work (but should)
* third message: `/np` but with mods selected and while playing so np actually reports the mods - works
  * also works in api: `https://api.tillerino.org/beatmapinfo?k=***&beatmapid=746471&mods=24` gives results
* fourth message: `/np` with other mods, but now it doesnt work, and neither does api

WithHandler is somehow doing weird?

Oppai should be able to get that last result?

**Comment by Tillerino** [comment]
Fixed
