### ISSUE TITLE
loved diff doesnt work, other (not loved) diffs do

### ISSUE THREAD

**Issue by omkelderman** [Tillerino/Tillerinobot#129]
![screenshot](https://puu.sh/unw7n.png)
same map-set: https://osu.ppy.sh/s/25739

tillerino-api has same behaviour

**Comment by Tillerino** [comment]
Can you tell me the beatmap IDs?

**Comment by omkelderman** [comment]
https://osu.ppy.sh/b/87570&m=0 tag4 diff, has the "This map is in a LOVED state" thing, others dont. That diff is the only diff the bot cannot handle.

![screenshot](https://omk.pics/1/abvPG.png)

unrelated sidenote: taiko diff gets completely ignored ![LUL](https://cdn.betterttv.net/emote/567b00c61ddbe1786688a633/1x)

**Comment by Tillerino** [comment]
History: There were eight ranked/approved TAG4 maps: 27638, 35015, 87570,
24722, 29844, 58064, 27737, 48874. When the one guy came along and FCd one
of them on a touch tablet and made a fuckton of pp, the maps were excluded
from pp, but stayed ranked (or something). So they are currently _manually_
excluded from the pp computation. Now that they are _loved_, that is no
longer required. Note also how it says on the website that the maps were
_loved_ back in 2009/2010, which is clearly impossible.

I'll remove them from the manual exclusion.

**Comment by omkelderman** [comment]
![LUL](https://cdn.betterttv.net/emote/567b00c61ddbe1786688a633/3x)

**Comment by Tillerino** [comment]
Check pls

**Comment by omkelderman** [comment]
![nope](https://omk.pics/1/LAWkH.png)

**Comment by Tillerino** [comment]
all good now. /close

**Comment by omkelderman** [comment]
![gud](https://omk.pics/1/kedzr.png) :+1:

**Comment by omkelderman** [comment]
wait, this should be closed as it is resolved right?
