### ISSUE TITLE
Inactive time counter doesn't work properly

### ISSUE THREAD

**Issue by MrMorkat** [Tillerino/Tillerinobot#130]
![Welcome Message](https://omk.pics/5/ix0hY.png)

The inactive time counter doesn't work properly sometimes when using the TsundereGerman language.

The message above is supposed to come when you are inactive for less then 4 minutes, as seen in this picture 

![Code](https://omk.pics/5/X9u7S.png)

**Comment by omkelderman** [comment]
idk if this is a test-backend-thingy, but when I testrun it, every time the [`scheduleRegisterActivity`](https://github.com/Tillerino/Tillerinobot/blob/638c7308ea8abdd9fa172b6de3848380fca11a33/tillerinobot/src/main/java/tillerino/tillerinobot/IRCBot.java#L532) call is called earlier than the [`getLastActivity`](https://github.com/Tillerino/Tillerinobot/blob/638c7308ea8abdd9fa172b6de3848380fca11a33/tillerinobot/src/main/java/tillerino/tillerinobot/IRCBot.java#L611) call. Obviously resulting in an `inactiveTime` of something very short.

But I cant remember having this issue myself...

Maybe (probably?) the test-backend is a bit more deterministic and this happens there always, but in "real life" it happens "sometimes"?

Pure speculation this... @Tillerino backend stuff, halp

**Comment by Tillerino** [comment]
The backend behaves exactly as expected here. The asynchronous nature will
work differently with a real database tho. I'll fix it.
