### ISSUE TITLE
custom error message for "java.io.IOException: empty beatmap" errors

### ISSUE THREAD

**Issue by omkelderman** [Tillerino/Tillerinobot#131]
cuz they are happening more and more

**Comment by omkelderman** [comment]
idea:
upon download of map, md5 the result and check it against the `file_md5` property in api response and if its differnt error out with a "osu server is being poopy" error, otherwise continue

**Comment by Tillerino** [comment]
Yeah, an md5 check is required here.

**Comment by Tillerino** [comment]
AFAICT, this is no longer an issue
