### ISSUE TITLE
Why tillerino is offline?

### ISSUE THREAD

**Issue by kayrabCebll** [Tillerino/Tillerinobot#133]
Hey man tillerino is offline pls repair

**Comment by MrMorkat** [comment]
https://twitter.com/Tillerinobot

Please do not open GitHub issues for this kind of stuff

**Comment by kayrabCebll** [comment]
0h okay sorry

**Comment by Tillerino** [comment]
This is planned downtime. Follow on twitter for more updates.

**Comment by omkelderman** [comment]
or the discord server ^^
