### ISSUE TITLE
specify number of 100s/50s instead of acc in !acc

### ISSUE THREAD

**Issue by omkelderman** [Tillerino/Tillerinobot#136]
Instead of giving a accuracy, give an amount of 100s and/or 50s as parameter.

The actual accuracy that will be given to the pp-calc system must then be calculated using those inputs. Keeping in mind that currently it is also possible to give number of misses in !acc.

I dont know for sure if its possible since the accuracy formula requires you to know the total number of possible hits in a song and I dont know if that information is in the tillerino-database.

@Tillerino thoughts?

edit: and ofc current functionality just keeps working, this is additional functionality ofc 😄

**Comment by Tillerino** [comment]
If it works for the interface, why not?

**Comment by omkelderman** [comment]
well, the thing is, if someone is telling the bot an amount of 100s (and or 50s) instead of acc, bot has to calc acc by itself, and to do that it needs the total amount of possible hits (cuz acc-formula). So for now really specific question: does the bot know the hit-amount-count or whatever the crap you wanna call it for each beatmap? cuz if not we'd have to parse `.osu` files? It is in oppai output I think...

**Comment by Tillerino** [comment]
Yeah, it knows. You can see in the `PercentageEstimates` interface that the
50/100s are calculated from the accuracy. Instead you can add another
default method on the interface, which takes the number of 50/100s and
skips that step.

**Comment by omkelderman** [comment]
gotcha! I see.

Well then this should be fairly easy to do. Now a format to parse player input.
We currently have `!acc 97.5 821x 1m` being acc, combo, misses. For this we need to swap acc to 100s and 50s but keep combo and misses I guess. I dunno a good suffix for "100s" or "50s" that isnt numerical :stuck_out_tongue: so maybe just do this:

`!acc 10 20 300x 4m` being `10` 100s, `20` 50s, `300` combo and `4` misses. The fact that there are two whole numbers instead of acc should be enough to parse it out right?

But on the other hand its not very clear to the enduser what they are entering, but I have no idea how to do that in a sensible way...

Small sidenote: I'm guessing I can calc amount of 300s by doing `getAllObjectsCount() - amount100s - amount50s` right?

**Comment by Tillerino** [comment]
Correct.

I'd go for something like `!acc 100x50 20x100 300x 4x` since it is very
unclear which of the two numbers is 50s and which is 100s. The command is
_so specific_ that I don't worry about it being unpractical.

>

**Comment by omkelderman** [comment]
ok, sounds good! Will implement when I find time 😛
