### ISSUE TITLE
Bot shows inaccurate pp

### ISSUE THREAD

**Issue by rorre** [Tillerino/Tillerinobot#137]
as requested by @omkelderman  at Discord server

Using /np, 95% shows 140pp, but 95.51% and 238x combo get 139pp
![](https://cdn.discordapp.com/attachments/170195816965734400/315080436982218753/screenshot007.jpg)

but when using
```
!acc 95.51 238x 0m
```
It shows 141pp.
![](https://cdn.discordapp.com/attachments/170195816965734400/315081338724286464/screenshot008.jpg)

Note: 238x means this has 1x missing slider tail, FC in map has 239x combo
Reported by Dan05 at Discord Server

**Comment by omkelderman** [comment]
tldr:
* `/np` gives *140pp* for 95%
* actual pp gained is *139pp* ![](https://omk.pics/1/XvI3H.png)
* `!acc 95.51 238x 0m` gives *141pp*

**Comment by Tillerino** [comment]
See Francesco149/koohii#7

**Comment by bommy985** [comment]
its worse,
![image](https://user-images.githubusercontent.com/61766076/91245778-eaecbe00-e713-11ea-8701-6a9ecdece1e8.png)

**Comment by Tillerino** [comment]
@bommy985 lol, you're getting trolled by Tsunderino. Shoutout to @Apotrope

**Comment by Tillerino** [comment]
I'll just close this since it's years old and pp issues come and go.
