### ISSUE TITLE
[API] beatmap info endpoint returns 500 for pending/graveyard maps

### ISSUE THREAD

**Issue by blimmo** [Tillerino/Tillerinobot#147]
Making a request to the beatmap info endpoint about [this map](https://osu.ppy.sh/b/1148905) caused a 500 error with the text "request failed".

I also tested with [this map](https://osu.ppy.sh/b/1138123), [this map](https://osu.ppy.sh/b/1356148) and [this map](https://osu.ppy.sh/b/1173829) so I think it is because they are pending or graveyard.

I would expect a 404 or a 400 since it is certainly the client's fault for requesting an unranked beatmap.

**Comment by Tillerino** [comment]
For those maps the API should still return values based on oppai results.
I'll look into it. It is always possible that those Maps are simply broken.

**Comment by Tillerino** [comment]
1148905 is working
1138123 is working
1356148 is working
1173829 is working

I guess the move from Oppai to Koohii fixed this.
