### ISSUE TITLE
need to be able to handle null pp from oppai

### ISSUE THREAD

**Issue by omkelderman** [Tillerino/Tillerinobot#148]
as per https://github.com/Francesco149/oppai/issues/48#issuecomment-315058043:
> and I will probably return null in json when that happens

Meaning that the `pp` property in the `tillerino.tillerinobot.diff.Oppai.OppaiResults` class can potentially be `null`, which I dont think it can handle currently. `double` probably needs to be `Double` to handle the possible `null`, but I have no idea what and where else this has consequences.

**Comment by Tillerino** [comment]
The value isn't used anywhere, so that would be okay.

**Comment by omkelderman** [comment]
guess this can be closed now, since a) it wasnt an issue in the first place, and b) its not really being used anymore right? xD

**Comment by Tillerino** [comment]
Correct
