### ISSUE TITLE
KAGOCI (screwed up wiring) and PP calculations with limited data

### ISSUE THREAD

**Issue by Drunkguy101** [Tillerino/Tillerinobot#15]
[KAGOCI](http://puu.sh/f2w8j/8e09870207.jpg)

I'd just like to start off by saying that this isn't really an issue, more of a question: How does Tillerino calculate the PP of a map which hasn't been FC'd with given mods? i.e. cookiezi's Revolution Deathsquad @ 97.91 is said to be 420pp. Is this accurate?

**Comment by Tillerino** [comment]
KAGOCI thing was fixed.

To answer your question: The pp values are accurate even if they are higher than any existing score. Errors happen now and then if the existing scores are somehow inconsistent. For example, there are beatmaps where scores exist, which have a higher max combo than is possible. This messes with the calculations.

This is what you can do to make sure: if you know the pp for one score and tillerinobot gives the correct pp for this score (mods+acc combination), then other accuracies for the same mods will be correct as well.
