### ISSUE TITLE
Have pp based recomendation?

### ISSUE THREAD

**Issue by ArchyInUse** [Tillerino/Tillerinobot#177]
this is just a suggestion, have command argument for !r {pp} where the bot can recommend a random map from n-10 to n+10 pp (where n is the argument given)

for example: !r 300

**Comment by Tillerino** [comment]
Hi Archy. So I guess my question here is: what do you want to achieve?

**Comment by ArchyInUse** [comment]
can you clarify the question? I was just recommending a feature, if it wasn't clear what I meant by a "random map from n-10 to n+10 pp" is if I type !r 300 the bot will return to me a map that if fc'd at a decent accuracy (98%-100%) will give me around 300pp.
Does this make sense?

**Comment by Tillerino** [comment]
I mean what's the story? Why would you want recommendations around a specific pp level?

**Comment by ArchyInUse** [comment]
Ahh, well I'm a returning player and I've decayed overtime, it doesn't help that before that I stopped playing online so my skill level doesn't match quite well with my rank, almost half a year of improvement not going into ranked so yeah that's the story

**Comment by Tillerino** [comment]
We have something along those lines on the radar, see #11 :P

This issue will be referenced there if we need some more inspiration. Other than that I'll close this as a duplicate then :)

**Comment by ArchyInUse** [comment]
in that case could you elaborate a little bit about how the recomendation system works? I'd like to try programming something like this for myself and it would be of great help

**Comment by Tillerino** [comment]
It's a statistical model of the kind if-you-liked-this-you-will-also-like-that. So similar to what amazon.com or Netflix do for their recommendations. There is no feature extraction or any other sort of dimensionality reduction going on, so I guess it's quite unique in that regard.
