### ISSUE TITLE
Tillerino will never recommend a map, no matter how many resets.

### ISSUE THREAD

**Issue by BruceGamez** [Tillerino/Tillerinobot#180]
This issue has been persisting with me for a while, I don't understand why or how, but it's stuck on this.
osu: https://osu.ppy.sh/users/10357391
![screenshot392](https://user-images.githubusercontent.com/31395352/68553827-f7549400-03e9-11ea-84d4-cc08d435f5f8.jpg)

**Comment by Tillerino** [comment]
Hi Bruce,

thanks for your report. I suspect that this has something to do with your top scores being fairly new and the pp changes earlier this year. The current recommendation model has not been adapted to these changes. A new version of the model has been trained recently and is [currently being tested with our Patrons](https://www.patreon.com/posts/updated-31254688). Please have a little patience until the new model is generally available. I'll leave this open until then.

Kind regards

Tillerino

**Comment by BruceGamez** [comment]
![screenshot396](https://user-images.githubusercontent.com/31395352/68988741-a685d680-0801-11ea-981f-a47c936e9640.jpg)
So can you explain why it used to work back then, even with the new scores, and why it won't recommend me any map with mods too?

**Comment by Tillerino** [comment]
Looks like this resolved itself
