### ISSUE TITLE
Beatmap corrupt when it is not corrupt.

### ISSUE THREAD

**Issue by lualex403** [Tillerino/Tillerinobot#187]
https://osu.ppy.sh/beatmapsets/1211207#osu/2521604 when I try to use tillerino for the extra difficulty it says the beatmap is corrupt however, when I copy and paste the difficulty and change the name, it works once, then when i try again it says beatmap corrupt

**Comment by Tillerino** [comment]
Weird, lemme take a look.

**Comment by Tillerino** [comment]
Hi @lualex403, I could not reproduce the problem. Can you send a screenshot of what you're doing or something?

**Comment by Tillerino** [comment]
Gonna close this since no follow-up
