### ISSUE TITLE
Tillerino /np doesn't work with mods

### ISSUE THREAD

**Issue by naemwear** [Tillerino/Tillerinobot#201]
Usually when you message Tillerino /np it will send you a message saying how much pp the map you are currently listening to will give also the mods you use will be included BUT I was playing a map called Xue Mao Jiao top dif (https://osu.ppy.sh/beatmapsets/789103#osu/1677982) a DT farm map, I watched a video saying an FC can give you 100+pp so typed to Tillerino /np to see how much 95% acc gives but it only gave me the stats for NM. I decided to try fieryrage's anime ban (https://osu.ppy.sh/beatmapsets/1178935#osu/2469345) top dif and Tillerino gave me the same pp for NM and DT. I decided to try the other mods (HR, HD) and it is the same
![Screenshot_454](https://user-images.githubusercontent.com/84918419/120067018-19703e80-c082-11eb-9549-d33a20af47dc.png)
![Screenshot_455](https://user-images.githubusercontent.com/84918419/120067020-1aa16b80-c082-11eb-9599-fe6a7a1ffe08.png)

**Comment by Striikerr** [comment]
I’m not a dev for tillerino, but from what i can gather from the screenshots you’ve sent. You’re doing /np while in the song select screen, when using /np like this (regardless of what mods you have pre selected) it will always return the nm values, if you want to know the DT performance (in your case anyway) you should type !with DT after you have already sent tillerino /np. I.e

You: /np
Tillerino: nm response
You: !with dt
Tillerino: dt response

while in song select, or do /np while actually playing the map with mods. (I cant close this issue but I'm 90% certain this is the answer one of the devs would give you, i doubt the map is bugged)

**Comment by Tillerino** [comment]
Yes, precisely. @naemwear please confirm that it works the way @Striikerr described

**Comment by naemwear** [comment]
I tried doing /np for the same song then !with DT and it did return a message giving different values. So yes you can close the case
![Screenshot_456](https://user-images.githubusercontent.com/84918419/120076074-8f899b00-c0ac-11eb-812d-dc727a9f324d.png)

**Comment by Tillerino** [comment]
alright
