### ISSUE TITLE
PP Calculation for non 100% scores is wrong

### ISSUE THREAD

**Issue by Schmittma** [Tillerino/Tillerinobot#217]
All given PP values (Both !r and /np) seem to be off compared to the actual numbers. Sometimes even massively.

Two examples:
[Reign of Fear](https://osu.ppy.sh/beatmapsets/347136#osu/811925) [III]
Tillerino: 95%: 115pp | 98%: 192pp | 99%: 237pp | 100% 294pp
Real score: 99.07%: 263pp

[Shinbatsu o Tadori Kyoukotsu ni Itaru](https://osu.ppy.sh/beatmapsets/482382#osu/2040764) [Extra Collab]
Tillerino: 95%: 126pp | 98%: 215pp | 99%: 276pp | 100% 343pp
Real score: 96.74%: 255pp
 
Somehow i didn't find anything related to this in the other issues, in the discord or in the forum.
I'd love to fix this myself, however it doesn't seem to be the implementation of the actual calculation, as it is basically equal with the stable implementation and other third-party calculators (e.g. rosu-pp). And i can't seem to be able to debug the behavior with a real map.

**Comment by Tillerino** [comment]
Hi Marius,

I know of one issue which is basically unfixable: accuracy is not precise enough to determine a pp value. In the latest pp formula, the number of 50s is used independently from the accuracy. To calculate pp, we try to guess a good number of 100s and 50s to match an accuracy but this will almost certainly be wrong. I have done some statistical analysis to see if there are typical 100s and 50s for a given accuracy, but so far haven't implemented anything based on that.

Have you tried inputting 100s and 50s directly and are there still deviations if you do that?

**Comment by Schmittma** [comment]
Inputting the exact number of 100s and 50s indeed resolves most of the deviations.

Same examples as before with exact inputs:
[Reign of Fear](https://osu.ppy.sh/beatmapsets/347136#osu/811925) [III]
!acc 18x100 0x50 1936x 0m -> 263pp

[Shinbatsu o Tadori Kyoukotsu ni Itaru](https://osu.ppy.sh/beatmapsets/482382#osu/2040764) [Extra Collab]
!acc 58x100 3x50 2213x 0m -> 236pp

In the second case, the difference comes from dropped combo in sliders. When a combo of 2221 (true full combo) is used, the output is 256pp as expected.

**Comment by Schmittma** [comment]
This at least clears up to me, where the deviation comes from in the code. I'm definitely going to try playing around with your current solution and see if i find ideas on how to make it more accurate.

**Comment by Tillerino** [comment]
The current code matches the accuracy as closely as possible (and quite quickly, too, which was fun to implement).
I think the most practical approach would be to just use 300s and 100s down to 33% and then use 50s and 100s. This isn't perfectly realistic, though. 50a usually sneak in at higher accuracies. I looked at a random sample of real scores trying to determine the relationship. If you want, I can send you the data.

**Comment by Schmittma** [comment]
After playing around with the function, it seems that the function outputs a significant amount of 50s compared to 100s.

When trying to calculate a value pair for [Shinbatsu o Tadori Kyoukotsu ni Itaru](https://osu.ppy.sh/beatmapsets/482382#osu/2040764), the function assumes 7x100s and 81x50s. As you said, this results in the best approximation for the given accuracy. I've also tested this with other accuracy and object-count combinations, and the results had always far more 50s than 100s.

As you mentioned, using only 100s is quite unrealistic. However, matching the accuracy exactly, hurts the PP calculation significantly more than being off by a few 50s (Which can be seen in the initial comparison).

While trying to understand the code, I noticed that the initial guess for the 300s is off by a few values (e.g. 1212 instead of 1200) compared to the actual numbers. This initial "error" seems to not be properly corrected afterwards and subsequently produces the mentioned estimates. When manually entering the "correct" value (from real world examples), the function seems to calculate the needed 100s significantly more accurate and often even matches the real world values. Of course, guessing the correct number of 300s is the hard part here.

As a comparison, I looked up the way, how rosu-pp handles this problem. Most of the initial guesses are the same, however, after calculating the 100s, they replace every 4 50s with 5 100s and accordingly reduce the number of 300s. Using a similar approach directly after the initial 300s estimate leads to an initial guess which seems to mostly match the real world values i was testing with. Although this seems to keep the number of 50s quite low as a result (often between 2 and 5).

This was all just quick testing, and as I'm not that experienced with the topic at hand, I can't really make an assertion on how to continue with the findings.

**Comment by Schmittma** [comment]
I rechecked the original values after the latest change in https://github.com/Tillerino/Tillerinobot/commit/8c1fbea9ed6be6424fc46fc3c4e7d0136cf0c84b#diff-5720af4c45fdd39d7c8da866a0223feb2edc1ff79dbe62382cb504f5e429683c

Especially on [Shinbatsu o Tadori Kyoukotsu ni Itaru](https://osu.ppy.sh/beatmapsets/482382#osu/2040764) [Extra Collab] this problem was the most pronounced due to the heavy influence on accuracy PP.

The bot now suggests the following PP values (Note that the initial values were pre-rework):
Tillerino: 95%: 190pp | 98%: 258pp | 99%: 292pp | 100% 339pp

Testing with !acc 96.74 matches the real world exactly:
![image](https://user-images.githubusercontent.com/20574467/202920267-c923fb1d-486e-430c-9f50-57da6085f5af.png)
Real world score:
https://osu.ppy.sh/scores/osu/4251898309

As such. This issue seems to be fixed.

**Comment by Tillerino** [comment]
Very nice, thank you!
