### ISSUE TITLE
Recommendations

### ISSUE THREAD

**Issue by StrawbxrryLiah** [Tillerino/Tillerinobot#223]
I stopped playing Osu for a while and started back up again. Tillerino is recommending songs I can't play anymore. Like 4-5 stars now, when I'm only able to play 3-4 stars right now. Is there a way to fix this? I tried !reset, but then realized that's not what it's for, and its against Osu TOS to make a new account. So I'm unsure of how to solve this problem. Thank you!

**Comment by Tillerino** [comment]
I've been looking into this. There is currently a feature being tested with Patreons where you can go `!r succ` that tunes down recommendation difficulty.

I'll be closing this issue for now since #11 has been around for a while.
