### ISSUE TITLE
Add an option to set the default recommendation options

### ISSUE THREAD

**Issue by ThePooN** [Tillerino/Tillerinobot#33]
Example:
I'm a nomod player, instead of doing "!r nomod" each time I want to use only "!r" without giving me DT, HR and such. Only nomod, as I would get "!r nomod".

I could set this option with: 
"!set defaultRecommandationSettings nomod"

Would love to have this. :) (i hope you understood me, English isn't my native language and i'm only 15. :P)

**Comment by omkelderman** [comment]
I think this would be a great addition, I'm supporting this! I would also suggest adding something like "!r mods" which does just exactly what !r does now without arguments, but you need it if you want to override the default.
(oh and don't worry about your English, nothing wrong with it)

**Comment by EnderAPOX** [comment]
Umm... yeah this seems like a great idea. I will create a pull request and add this hopefully. The commands will be:
- !setrecommendmods mods
- !setrecommendmods nomods

**Comment by Tillerino** [comment]
Please extend the existing !set and !view commands :)

**Comment by EnderAPOX** [comment]
Well having some problems with this since you actually need to save the bool somewhere. I might do this in the weekend.

**Comment by ChemiHatake** [comment]
Assuming no one is working on this given how old this issue is, I will start working on it.

**Comment by Tillerino** [comment]
👍

**Comment by ChemiHatake** [comment]
@Tillerino Wasn't able to set up the project,
(I followed the video in the wiki)

**Comment by Tillerino** [comment]
What's the problem?

**Comment by ChemiHatake** [comment]
@Tillerino Just restarted the PC and getting no errors now.
will start working on it.

**Comment by ChemiHatake** [comment]
@Tillerino 
So I've just finished debugging,
it works but I had to make the RecommendationsManager get 4 variables instead of 3
(will now need to get the UserDataManager for the recommendMods setting value) 

does that mean I need to change anything in the non test IRCBot class?
because I had to change it in few of the test classes.
(it doesn't throw any errors)
