### ISSUE TITLE
Tsundere language doesn't clear lastRecommendation when invalid mods are requested

### ISSUE THREAD

**Issue by ScoreUnder** [Tillerino/Tillerinobot#48]
It looks like if someone runs `!complain` on one of the tsundere fake-recommendations, it will complain about the last map actually recommended instead.

I've tried to test this (22:05 UTC) but only you can see the logs to know if it actually happened.

**Comment by ScoreUnder** [comment]
![Screenshot](https://i.imgur.com/u9WysI3.png)

**Comment by ScoreUnder** [comment]
```
!r
00:58:31.022 INFO  IRCBot test - received: !r
Tillerino: [http://osu.ppy.sh/b/100858 DragonForce - Beatmap 100858 [Hard]]   future you: 52pp | 95%: 45pp | 98%: 53pp | 99%: 56pp | 100%: 59pp | 6:49 ★ 2.88 ♫ 129.16 AR7 ♥
00:58:31.533 INFO  IRCBot test - sent: [http://osu.ppy.sh/b/100858 DragonForce - Beatmap 100858 [Hard]]   future you: 52pp | 95%: 45pp | 98%: 53pp | 99%: 56pp | 100%: 59pp | 6:49 ★ 2.88 ♫ 129.16 AR7 ♥
!r testing
00:58:34.456 INFO  IRCBot test - received: !r testing
Tillerino: [http://osu.ppy.sh/b/52405 Within Temptation (feat. Keith Caputo) - What Have You Done [Normal]]   95%: 12pp | 98%: 16pp | 99%: 19pp | 100%: 24pp | 4:56 ★ 2.26 ♫ 172 AR5 ♠
00:58:34.954 INFO  IRCBot test - sent: [http://osu.ppy.sh/b/52405 Within Temptation (feat. Keith Caputo) - What Have You Done [Normal]]   95%: 12pp | 98%: 16pp | 99%: 19pp | 100%: 24pp | 4:56 ★ 2.26 ♫ 172 AR5 ♠
!complain twelve pp you what mate
00:58:49.954 INFO  IRCBot test - received: !complain twelve pp you what mate
00:58:49.963 WARN  IRCBot test - COMPLAINT: 100858 mods: 0. Recommendation source: []
Tillerino: Whaaaat!? How could you say something like... oh, that beatmap? Actually that's there because I hated it and wanted to test you. Aren't you glad having something in common with me?
00:58:50.028 INFO  IRCBot test - sent: Whaaaat!? How could you say something like... oh, that beatmap? Actually that's there because I hated it and wanted to test you. Aren't you glad having something in common with me?
```

Tested with the test backend, and as I thought it's complaining about the real rec rather than the fake.

**Comment by Tillerino** [comment]
Yeah you're right, nothing is happening as expected there. But I've actually never statistically evaluated complaints or anything, so this is not a big deal.

Anyway, a fairly clean solution would be to add `UserData` to `Language.invalidChoice`, and clear `UserData.lastSongInfo` when a troll recommendation is given. Any `!complain` should then be silently ignored until an actual recommendation is given.

If you want to add a gotcha-response, you could change `UserData.lastSongInfo` to `0/0`, prevent logging for that value, pass it to `Language.complaint` and send a response anyway.

Changing the `Language` interface is no problem as long as you only pass data and not something like `IRCBot` or `RecommendationsManager`.

**Comment by Tillerino** [comment]
This is not worrying enough to warrant working on it, since it would require a datastructure for this sole purpose.
