### ISSUE TITLE
Feature: Alias NC to DT

### ISSUE THREAD

**Issue by ScoreUnder** [Tillerino/Tillerinobot#49]
`!r nc` is currently unrecognised, but it would be fine to just consider `nc` the same as `dt`

**Comment by ScoreUnder** [comment]
Added a patch. As with #50, the same warning applies that I can't test it.

Here I've just aliased nc to dt, since they're essentially the same mod. If that's the wrong thing to do I'll fix that up.

**Comment by Tillerino** [comment]
I don't have a strong opinion on this. If you open a pull request, I'll merge it.
