### ISSUE TITLE
Determinism in Tsundere class

### ISSUE THREAD

**Issue by ScoreUnder** [Tillerino/Tillerinobot#50]
In `Tsundere#invalidChoice(String, String)` there is a deterministic test commented with:

> non-randomness required for unit test

Maybe you can move the randomness into a method like `protected boolean shouldGiveFakeRecommendation()` and override its behaviour for the unit test (since the randomness isn't the bit that needs testing, I hope).

**Comment by ScoreUnder** [comment]
^ The above commit might or might not work. I'm unable to test as I don't have an osu api key

*insert grumble about that aussie dude here*

**Comment by TheHowl** [comment]
>I don't have an osu api key

uhhh??? http://osu.ppy.sh/p/api

it's literally 2 clicks away

**Comment by omkelderman** [comment]
there is a way to test-run tillerinobot tho, idk what you are trying to achieve, but have a look at https://github.com/Tillerino/Tillerinobot/wiki/Working-on-Tillerinobot

@TheHowl, you cannot use your own api-key to testrun Tillerino tho, see my first sentence.

**Comment by ScoreUnder** [comment]
> uhhh??? http://osu.ppy.sh/p/api
>
> it's literally 2 clicks away

That link was redirecting me away to the forums a minute ago. Not sure what was going on there.

**Comment by ScoreUnder** [comment]
@TheHowl if you have an API key, could you comment on if what I'm seeing is expected behaviour? You said it's 2 clicks away, but the wording of the form strongly implies that it must be manually reviewed by someone "up there" before any key is given out. Is that what happens? Am I meant to see some sort of confirmation when clicking the submit button?

**Comment by Tillerino** [comment]
@Apotrope did you originally want this to behave randomly instead of in a troll-troll-troll-help pattern?

**Comment by Tillerino** [comment]
@ScoreUnder I remember getting an API key instantly.

**Comment by Apotrope** [comment]
@Tillerino I think it was originally all troll messages, but it was soon changed the troll-troll-troll-help pattern so it wouldn't be excessively confusing. I don't think it was ever actually random (the comment doesn't necessarily imply it), but maybe it was. 

Either way, deterministic is probably better anyways - first to allow for the joke a few times, rather than potentially giving a help message right away; and second to prevent being redundant by potentially giving the help message multiple times in a row.

**Comment by Tillerino** [comment]
I like the reliability, too. So I guess we'll leave it as it is. (Although tbh I feel like we're making too big a deal out of this either way)

**Comment by omkelderman** [comment]
> Although tbh I feel like we're making too big a deal out of this either way

That's for sure ^^

**Comment by ScoreUnder** [comment]
No such thing as too big a deal -- good, better, best and all that.

Since the current behaviour is the intended behaviour I'll close the issue.
