### ISSUE TITLE
Completed songs are recommended

### ISSUE THREAD

**Issue by ScoreUnder** [Tillerino/Tillerinobot#51]
![Screenshot of chat log](https://i.imgur.com/xUexlDW.png)
![Screenshot of score from recommended song](https://i.imgur.com/jApjBFP.png)

I got a recommendation for "Leave the Lights On" which was an unusually easy 88pp for me. I asked the bot what PP I would get in HD and it gave me some estimates (which I then used as an excuse to throw away some low-PP HD plays). After not beating my original score I asked for another recommendation, but got the same song -- and it thought "future me" would do worse!

**Comment by Tillerino** [comment]
I checked the log and conclude that you didn't click the second link. It was a different beatmap: http://osu.ppy.sh/b/217253 An indicator for that would also have been the different star dificulty (4.07 vs 4.3). It's weird that the special chars don't show up in your client tho.

**Comment by TheHowl** [comment]
Perhaps he's running osu! on linux? I remember font rendering issues on it.

Il 03/07/2015 12:54, Tillerino ha scritto:

**Comment by ScoreUnder** [comment]
> Perhaps he's running osu! on linux? I remember font rendering issues on it.

Yeah, this is the cause of missing special characters

> It was a different beatmap

Well spotted, I'll close this then.
