### ISSUE TITLE
Add a value in !r command to ask for X pp maps or higher 

### ISSUE THREAD

**Issue by Cleverdawn** [Tillerino/Tillerinobot#65]
Hi :3 Thx for everything with TillerinoBot :D
A value to specify the pp minimum we get at 95% would be very handy : 
for exemple, "!r dt 150" would show you a map that give at least 150 pp at 95%
It would be very usefull for all the maps that tillerino give me that are under 130 pp at 95% :v
And a value to specify the max length of a song would be awesome too but eh :v

**Comment by Tillerino** [comment]
I something cooking, which adjusts the difficulty of the recommendations, but not in this form.
