### ISSUE TITLE
MAYBE ADD A FUCKING TUTORIAL

### ISSUE THREAD

**Issue by FleX116** [Tillerino/Tillerinobot#80]
LIKE FUCKING IDIOTS LIKE ME CANT ISNTALL THIS SHIT. MAYBE ADD A FUCKING TUTORIAL IN UR WIKI YOU SHITBAGS

**Comment by thehowl** [comment]
Hello! Welcome to GitHub. GitHub is a website where developers can share code with other developers through the command line application `git`. Non-developers usually sign up on the website to report bugs on websites where the preferred way of reporting bugs is using GitHub. Apart from that case, usually users of this website are assumed to have some technical knowledge on how to set up projects. Should they have any issues during installation, they may be invited to open an issue asking on how to specifically do something, in a civil and educate manner.

Please come back when you have the slightest idea of what you're doing.

**Comment by thehowl** [comment]
Also, a question: why do you need to install this? To make your own FleX116Bot? For what reason, if I may ask?

**Comment by Tillerino** [comment]
Lol here you go buddy https://www.youtube.com/watch?v=pFyQs3wwuZg

**Comment by Tillerino** [comment]
And here https://www.youtube.com/watch?v=ppcSB-_Wcos

or here https://www.youtube.com/watch?v=RgvguOMi7Us

Just search `Tillerino` or `Tillerinobot` on youtube there are quite a few of these.
