### ISSUE TITLE
!r HR should not bring up HDHR maps and !r HD should not bring up HDDT maps

### ISSUE THREAD

**Issue by Tyrrrz** [Tillerino/Tillerinobot#86]
That's how I see it at least.
When I search for HD i want to have HD recommendations, not HDDT or HDHR, otherwise i would've searched for those combinations instead.

**Comment by omkelderman** [comment]
This was requested before, see #64. The solution is to exclude non-wanted mods with the "exclude mod filter". See https://github.com/Tillerino/Tillerinobot/wiki/Recommendations#filters

Note that filters only work for tillerino-donators.
