### ISSUE TITLE
!with hddt/hdhr/hddthr works, !with dt does not

### ISSUE THREAD

**Issue by omkelderman** [Tillerino/Tillerinobot#98]
![](https://cdn.discordapp.com/attachments/170177781257207808/232873957219368960/screenshot006.jpg)

beatmap: https://osu.ppy.sh/b/785097

**Comment by Tillerino** [comment]
Oh man the spacetime continuum went Kappa right there. Should be fixed.

**Comment by omkelderman** [comment]
> Should be fixed.

confirmed fixed
